### ISSUE TITLE
Checklist, possible to use existing checklist

### ISSUE THREAD

**Issue by nullkaaryle** [labtool/labtool#111]
This story includes adding the following features:

* Each course instance's each week has its own checklist. It is empty by default.

Teacher can

## Use a checklist

When the teacher is reviewing a student, they see a checklist on the right side of the comment and points fields. The checklist displays the categories of the tasks, and each task under the category it belongs to.

There is a text field on the right side of the checklist. The contents of the text field changes according to what boxes are checked (just like in the current Labtool).

Under the checklist, a point total is displayed. The point total changes according to what boxes are checked, i.e. what tasks are fulfilled.

After choosing the checklist and marking the check-boxes to their will, the teacher can copy the text from the text field and paste it to the feedback field and edit it. The points total is automatically copied to the points field, but it can be edited too before submitting.

**Comment by ruupert** [comment]
Could perhaps somehow be implemented by accepting markdown as input ?
