### ISSUE TITLE
Getting all studentinstances with courseinstance id

### ISSUE THREAD

**Issue by laatopi** [labtool/labtool#121]
Mahdollisuus hakea bäkkäriltä kaikki tietyn courseinstancen studentinstancet kyseisen courseinstancen idllä.

Eli jos Tiralabra courseinstancella on 3 studentinstancea, saadaan nämä 3 SI haettua bäkkäristä tiralabran CI id:llä.

**Comment by ruupert** [comment]
If Sequelize is anything like in RoR, then its just about making a model function that delivers just that.

**Comment by ruupert** [comment]
Like then you could simply ask from the model CourseInstance.getTheThing(params) and just return that.
