### ISSUE TITLE
Check if user is {registered, student, teacher} on a specific Course Instance

### ISSUE THREAD

**Issue by laatopi** [labtool/labtool#130]
Kysely jossa lähetetään Userin tokeni, opetushallitus kurssi Id, ja palauttaa tiedon onko käyttäjä rekisteröitymätön, opiskelija, vai opettaja kyseisellä kurssilla.

Esim. POST jnqwiou90wqh TKT20011.2018.K.K.2

vastaus voisi olla
 {unregistered}, {teacher}, {student} tms mitä vaan millä saa selvää.

**Comment by NorthernLion** [comment]
GET
    OHID, TOKEN
        IF (TEACHER)
            {
                                
                role: teaher,
                Student Instances: [Student Instances]
                    .. weeks: [Weeks]
            }
        IF (STUDENT)
            {
                                
                role: student,
                Student Instance: Student Instance
                weeks: [Weeks]
            }
        IF (NEITHER)
            {
                NOTHINGLESS
            }

**Comment by ruupert** [comment]
I'll try to implement this as a model method in courseinstance and let the courseinstance controller return that.

**Comment by ruupert** [comment]
seems like pumm1 & laatopi is doing this so no point going forward on branch  4_130_get_a_blob_that_satisfies_issue_130
