### ISSUE TITLE
Hidden comment bug

### ISSUE THREAD

**Issue by pumm1** [labtool/labtool#219]
`include: [
              {
                model: Comment,
                as: 'comments',
               where: {
                   hidden: false
              }
              }
]`

This `where` causes the coursePage not to work for some reason, so for now we shouldn't allow teachers to have hidden comments (as students can now see the comments). For now the `where` is taken away and frontend should just have the default value to be false for the hidden status.

**Comment by NorthernLion** [comment]
This bug is solved very good back
