### ISSUE TITLE
Adding a new email when using Labtool the first time contains a few bugs and some inadequate validation

### ISSUE THREAD

**Issue by laimikko1** [labtool/labtool#231]
The cancel button does nothing on the front page.

![bugikuva1](https://user-images.githubusercontent.com/19820360/40307459-49b90f5a-5d0b-11e8-82f5-61f7060bb587.png)

The user can send an empty email address, it's not validated. After this I couldn't access my own page etc, it just prompted me to adding a new email the next time I logged in. (As is the intended usage)

![bugikuva2](https://user-images.githubusercontent.com/19820360/40307590-cb8d5a9a-5d0b-11e8-8663-2bd5d9f6d021.png)

When I sign and havent' added an email address yet, the instructions say "Edit your email address" instead of saying "Add email address" etc. You can see this on the first image too

Mikko

**Comment by Chamion** [comment]
Adding to this: inputting too long an email will have the backend reject it, but the frontend will still act as if a valid email was entered.

![screenshot](https://i.gyazo.com/32ea2cf1917f640b7201eb80a2a1d5b9.png)
