### ISSUE TITLE
Script import_courses does not create teacher instances

### ISSUE THREAD

**Issue by ValheKouneli** [labtool/labtool#242]
npm run create_courses _does_ import courses, but unlike importing courses by hand at the admin page, the script does not create teacher instances (based on information received from kurki)

**Comment by ruupert** [comment]
yes that method was how we used (before the admin page thing) to import courses into the local development db to have something to work with, but this method as is isn't something the complete application should have available.

**Comment by ruupert** [comment]
meaning that at least the update path should not be available to users that are not allowed to do that. currently that action just checks that the user is logged in and then proceeds to import and update or create the course db entries.
