### ISSUE TITLE
Students' course review targets can be generated by tags

### ISSUE THREAD

**Issue by ValheKouneli** [labtool/labtool#284]
Part of the Course review feature

When implemented:

* Course C's assistant A have a way, on the webpage, to see all the tags that this course's projects have. On the webpage, A can choose a tag or tags, and by pressing a button, all the student's whose projects have one of the chosen tags, are randomly assigned to review each other.

**Comment by Chamion** [comment]
Already implemented, just needs bugfixes to be considered done.
