### ISSUE TITLE
In the readme or wiki, there should be a link to documents that do not belong in the wiki but are relevant to this Ohtuprojekti

### ISSUE THREAD

**Issue by ValheKouneli** [labtool/labtool#316]
These document include:

* Information and instructions related to the test environment (test server and dockerhub) we use in this Ohtuprojekti
* Instructions on how to demo the project (for the ease of possible future ohtuprojekti teams)
* If wanted, info related the the team's time usage, responsibilities in each sprint, client meetings and retrospectives

**Comment by Chamion** [comment]
#273
