### ISSUE TITLE
Adding assisting teachers' needs visual adjustments regarding shown information

### ISSUE THREAD

**Issue by maarila** [labtool/labtool#323]
The page where a teacher can add other teachers to the course needs a few visual adjustments.

* Title header should be the name of the course, not 'Users'.
* Names should be organised alphabetically, and in the form Lastname, Firstname(s)
* Only the persons responsible for the course (i.e. those known by Kurki) are named 'admin', the rest should be name 'teacher'.

**Comment by ootee** [comment]
Fixed with several PRs
