### ISSUE TITLE
If comment is has a really long (wide) line of code, there is no way to scroll sideways

### ISSUE THREAD

**Issue by ValheKouneli** [labtool/labtool#358]
How to replicate:
* As a teacher/assistant, give student B a weekly feedback: \`\`\`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\`\`\` (No newlines at all)
* Comment the same week.
* Log in as student B and look at your feedback. Notice that you can not see all of it, and the comment does not show at all, because it is on the right side of the feedback, out of view.

**Comment by ootee** [comment]
Fixed with PR #367
