### ISSUE TITLE
When an official teacher of an imported course logs in for the first time, they have no name

### ISSUE THREAD

**Issue by ValheKouneli** [labtool/labtool#360]
How to replicate:
* Have a user U, who is a teacher on course C, and who isn't a student on any course, and who has never logged into the system
* Import course C
* Log in as user U (fill in your e-mail address) and view MyPage. It shows only a comma as your name.

This has a potential for crashing the system, because when a user leaves a comment, their real name is saved with the comment at the moment.

e. When the user logs in, their first and last names are update in the database. The problem is that they are not updated in the store before the next login.

**Comment by ootee** [comment]
Fixed with #476
