### ISSUE TITLE
fronend does not respect the react PUBLIC_URL env variable

### ISSUE THREAD

**Issue by ruupert** [labtool/labtool#65]
Issue description:  

Production server doesn't reside at the root of the host. The host also might be something different than in development. For that reason using PUBLIC_URL env variable this host and possible path can be specified the docker-compose.yml configuration or in development by telling the react thing its URL (if that was even nescessary in NODE_ENV=development. This feature was working before but something has changed. 

This might help to resolve this issue:

https://medium.com/@svinkle/how-to-deploy-a-react-app-to-a-subdirectory-f694d46427c1

**Comment by ruupert** [comment]
This is resolved ish ish. 🤕 🔨  

Should remain open until front end seems to be working on development test production environment.

**Comment by NorthernLion** [comment]
THIS WORKS

**Comment by NorthernLion** [comment]
ApiPath Magic has been enabled to combat this problem. Should be fixed in 4_02
