### ISSUE TITLE
Feature request: Use REACT_APP_BACKEND_URL for all requests

### ISSUE THREAD

**Issue by ruupert** [labtool/labtool#76]
Problem: 

Current development environment works only if the front end is run on localhost along with the backend. In the current production test server there's another path for the backend. 

In a local development environment scenario where the back and front end is not run on localhost from the browsers point of view, one has to go in and change the request urls in the labtool2.0/src/Login.js to something which is the actual host where the back end is. In the current docker-compose.yml file there is already an environment variable called REACT_APP_BACKEND_URL specified and documentated here: https://github.com/labtool/labtool/wiki/Deployment

Solution proposal:

Change the behaviour of these 

```javascript
    if (process.env.NODE_ENV === 'development') {
      backend = 'http://localhost:3001/api/users/update'
    } else {
      backend = '/labtool-backend/users/update'
    }
```
to
```javascript
backend = process.env.REACT_APP_BACKEND_URL + '/api/users/update'
```
or something similar (some check somewhere to see if the REACT_APP_BACKEND_URL is set, and if not then set it to default like http://localhost:3001) so that anyone can just specify where the backend is without having to change the front end code in any way.

**Comment by NorthernLion** [comment]
This has been fixed in branch Redux. For local development, you need to add REACT_APP_BACKEND_URL to .env file. Hopefully, it will be merged into dev by the end of the day.

**Comment by NorthernLion** [comment]
Fixed in 4_02 part of dev now
