### ISSUE TITLE
URL REQUEST

### ISSUE THREAD

**Issue by NorthernLion** [labtool/labtool#89]
Both of these urls given by backend do not exist. Why did backend team give these?

http://localhost:3001/api/course/teacher
http://localhost:3001/api/course/student

**Comment by ruupert** [comment]
must have been a mix up in the coffee machine. instead of mocha latte it gave chai tea. we will send our specialists to have a look at coffee maker.

**Comment by NorthernLion** [comment]
ok understand. fix please

**Comment by ruupert** [comment]
with careful analysis of the coffee maker, without consulting our board of directors, I deducted that the routes are present and the smoothie should mix correctly. It says in the hieroglyphics that the coffee maker doesn't accept any eager GETters but instead the bloody thing wants you to POST your request and wait for the order to complete. 

So I would want to further inquire on the matter that seems to be the problem. Could you please be more specific?

For your information, I was looking at the dev branch current organization!

**Comment by NorthernLion** [comment]
Frank says can make his own cofee now. We fixed

**Comment by ruupert** [comment]
Thats great to hear. I have no clue what the issue was and hence I will not be tuned to whatever this problem might have been, so in foresight, if something is not like you want it to be, regarding to this unknown issue, then keep in mind that necessary information was not passed in the first place.
